package systemd_service

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/warewulf/warewulf/internal/app/wwctl/overlay/show"
	"github.com/warewulf/warewulf/internal/pkg/testenv"
	"github.com/warewulf/warewulf/internal/pkg/wwlog"
)

func Test_systemdServiceOverlay(t *testing.T) {
	tests := map[string]struct {
		args      []string
		nodesConf string
		output    string
	}{
		"ww-service.ww: oneshot service": {
			args: []string{"--quiet=false", "--render=node1", "systemd.service", "etc/systemd/system/ww-service.ww"},
			nodesConf: `
nodes:
  node1:
    resources:
      systemd.service:
        site-tuning:
          Type: oneshot
          RemainAfterExit: "yes"
          ExecStart: /usr/local/sbin/site-tuning.sh`,
			output: `backupFile: true
writeFile: true
Filename: site-tuning.service

# This file is autogenerated by warewulf

[Unit]
Description=Warewulf-managed service: site-tuning
After=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/local/sbin/site-tuning.sh

[Install]
WantedBy=multi-user.target
`,
		},
		"ww-service.ww: service with custom Description and After": {
			args: []string{"--quiet=false", "--render=node1", "systemd.service", "etc/systemd/system/ww-service.ww"},
			nodesConf: `
nodes:
  node1:
    resources:
      systemd.service:
        my-daemon:
          Description: My custom site daemon
          After: network.target
          ExecStart: /usr/local/bin/my-daemon
          Restart: on-failure`,
			output: `backupFile: true
writeFile: true
Filename: my-daemon.service

# This file is autogenerated by warewulf

[Unit]
Description=My custom site daemon
After=network.target

[Service]
ExecStart=/usr/local/bin/my-daemon
Restart=on-failure

[Install]
WantedBy=multi-user.target
`,
		},
		"ww-service.ww: minimal service (defaults only)": {
			args: []string{"--quiet=false", "--render=node1", "systemd.service", "etc/systemd/system/ww-service.ww"},
			nodesConf: `
nodes:
  node1:
    resources:
      systemd.service:
        minimal: {}`,
			output: `backupFile: true
writeFile: true
Filename: minimal.service

# This file is autogenerated by warewulf

[Unit]
Description=Warewulf-managed service: minimal
After=network-online.target

[Service]

[Install]
WantedBy=multi-user.target
`,
		},
		"ww-service.ww: service with all fields": {
			args: []string{"--quiet=false", "--render=node1", "systemd.service", "etc/systemd/system/ww-service.ww"},
			nodesConf: `
nodes:
  node1:
    resources:
      systemd.service:
        full-service:
          Description: Full service example
          Type: oneshot
          After: network-online.target
          Before: shutdown.target
          Wants: network.target
          Requires: local-fs.target
          ConditionPathExists: /usr/local/bin/full-service
          RemainAfterExit: "yes"
          ExecStartPre: /usr/local/bin/full-service --check
          ExecStart: /usr/local/bin/full-service --start
          ExecStartPost: /usr/local/bin/full-service --post
          ExecStop: /usr/local/bin/full-service --stop
          WantedBy: multi-user.target`,
			output: `backupFile: true
writeFile: true
Filename: full-service.service

# This file is autogenerated by warewulf

[Unit]
Description=Full service example
After=network-online.target
Before=shutdown.target
Wants=network.target
Requires=local-fs.target
ConditionPathExists=/usr/local/bin/full-service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStartPre=/usr/local/bin/full-service --check
ExecStart=/usr/local/bin/full-service --start
ExecStartPost=/usr/local/bin/full-service --post
ExecStop=/usr/local/bin/full-service --stop

[Install]
WantedBy=multi-user.target
`,
		},
		"ww-service.ww: no resources (abort)": {
			args: []string{"--quiet=false", "--render=node1", "systemd.service", "etc/systemd/system/ww-service.ww"},
			nodesConf: `
nodes:
  node1: {}`,
			output: "backupFile: true\nwriteFile: false\nFilename: etc/systemd/system/ww-service\n\n\n",
		},
		"multi-user.target.wants/ww-service.ww: symlink": {
			args: []string{"--quiet=false", "--render=node1", "systemd.service", "etc/systemd/system/multi-user.target.wants/ww-service.ww"},
			nodesConf: `
nodes:
  node1:
    resources:
      systemd.service:
        site-tuning:
          ExecStart: /usr/local/sbin/site-tuning.sh`,
			output: `backupFile: true
writeFile: true
Filename: site-tuning.service

{{ /* softlink "/etc/systemd/system/site-tuning.service" */ }}
`,
		},
		"multi-user.target.wants/ww-service.ww: no resources (abort)": {
			args: []string{"--quiet=false", "--render=node1", "systemd.service", "etc/systemd/system/multi-user.target.wants/ww-service.ww"},
			nodesConf: `
nodes:
  node1: {}`,
			output: "backupFile: true\nwriteFile: false\nFilename: etc/systemd/system/multi-user.target.wants/ww-service\n\n\n",
		},
	}

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			env := testenv.New(t)
			defer env.RemoveAll()
			env.ImportFile("var/lib/warewulf/overlays/systemd.service/rootfs/etc/systemd/system/ww-service.ww", "../rootfs/etc/systemd/system/ww-service.ww")
			env.ImportFile("var/lib/warewulf/overlays/systemd.service/rootfs/etc/systemd/system/multi-user.target.wants/ww-service.ww", "../rootfs/etc/systemd/system/multi-user.target.wants/ww-service.ww")
			env.WriteFile("etc/warewulf/nodes.conf", tt.nodesConf)
			cmd := show.GetCommand()
			cmd.SetArgs(tt.args)
			stdout := bytes.NewBufferString("")
			stderr := bytes.NewBufferString("")
			logbuf := bytes.NewBufferString("")
			cmd.SetOut(stdout)
			cmd.SetErr(stderr)
			wwlog.SetLogWriter(logbuf)
			err := cmd.Execute()
			assert.NoError(t, err)
			assert.Empty(t, stdout.String())
			assert.Empty(t, stderr.String())
			assert.Equal(t, tt.output, logbuf.String())
		})
	}
}
