package chrony

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/warewulf/warewulf/internal/app/wwctl/overlay/show"
	"github.com/warewulf/warewulf/internal/pkg/testenv"
	"github.com/warewulf/warewulf/internal/pkg/wwlog"
)

func Test_ChronyOverlay(t *testing.T) {
	tests := map[string]struct {
		warewulf_conf string
		nodes_conf    string
		args          []string
		log           string
	}{
		"default": {
			warewulf_conf: `
ipaddr: 192.168.1.254
netmask: 255.255.255.0
network: 192.168.1.0
`,
			nodes_conf: `
nodes:
  node1:
    ipaddr: 192.168.1.10
`,
			args: []string{"--render", "node1", "chrony", "etc/chrony.conf.ww"},
			log: `backupFile: true
writeFile: true
Filename: etc/chrony.conf
# This file is autogenerated by warewulf
# Default to Warewulf controller
server 192.168.1.254 iburst

# Record the rate at which the system clock gains/losses time.
driftfile /var/lib/chrony/drift

# Allow the system clock to be stepped in the first three updates
# if its offset is larger than 1 second.
makestep 1.0 3

# Enable kernel synchronization of the real-time clock (RTC).
rtcsync

# Allow NTP client access from local network.
allow 192.168.1.0/24

# Specify directory for log files.
logdir /var/log/chrony

# Also include any directives found in configuration files in /etc/chrony.d
include /etc/chrony.d/*.conf
`,
		},
		"custom_servers": {
			warewulf_conf: `
ipaddr: 192.168.1.254
netmask: 255.255.255.0
network: 192.168.1.0
`,
			nodes_conf: `
nodes:
  node1:
    ipaddr: 192.168.1.10
    tags:
      ntp_servers: "10.0.0.1,10.0.0.2"
`,
			args: []string{"--render", "node1", "chrony", "etc/chrony.conf.ww"},
			log: `backupFile: true
writeFile: true
Filename: etc/chrony.conf
# This file is autogenerated by warewulf
server 10.0.0.1 iburst
server 10.0.0.2 iburst

# Record the rate at which the system clock gains/losses time.
driftfile /var/lib/chrony/drift

# Allow the system clock to be stepped in the first three updates
# if its offset is larger than 1 second.
makestep 1.0 3

# Enable kernel synchronization of the real-time clock (RTC).
rtcsync

# Allow NTP client access from local network.
allow 192.168.1.0/24

# Specify directory for log files.
logdir /var/log/chrony

# Also include any directives found in configuration files in /etc/chrony.d
include /etc/chrony.d/*.conf
`,
		},
	}

	env := testenv.New(t)
	defer env.RemoveAll()
	env.ImportFile("var/lib/warewulf/overlays/chrony/rootfs/etc/chrony.conf.ww", "../rootfs/etc/chrony.conf.ww")

	for name, tt := range tests {
		t.Run(name, func(t *testing.T) {
			env.WriteFile("etc/warewulf/warewulf.conf", tt.warewulf_conf)
			env.WriteFile("etc/warewulf/nodes.conf", tt.nodes_conf)
			// Reload configuration to pick up changes
			_ = env.Configure()
			cmd := show.GetCommand()
			cmd.SetArgs(tt.args)
			stdout := bytes.NewBufferString("")
			stderr := bytes.NewBufferString("")
			logbuf := bytes.NewBufferString("")
			cmd.SetOut(stdout)
			cmd.SetErr(stderr)
			wwlog.SetLogWriter(logbuf)
			err := cmd.Execute()
			assert.NoError(t, err)
			assert.Empty(t, stdout.String())
			assert.Empty(t, stderr.String())
			assert.Equal(t, tt.log, logbuf.String())
		})
	}
}
