#!/bin/sh

. /warewulf/config
# Only start if the systemd is no available
test -e /usr/lib/systemd/systemd && exit 0
echo "Starting wwclient"
nohup /warewulf/bin/wwclient >/var/log/wwclient.log 2>&1 </dev/null &
