#!/bin/sh
. /warewulf/config
# Only start if the systemd is no available
test -d /run/systemd/system  && exit 0
echo "Starting wwclient"
nohup /warewulf/wwclient >/var/log/wwclient.log 2>&1 </dev/null &

