{
 "title": "warewuf",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last seen",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "clamp_max(timestamp(max(warewulf_status_node_lastseen) by(nodeID)) - (max(warewulf_status_node_lastseen) by(nodeID)),60*60)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(warewulf_status_node_lastseen{stage=\"RUNTIME_OVERLAY\"})-(warewulf_status_node_lastseen{stage=\"RUNTIME_OVERLAY\"})",
     "legendFormat": "{{nodeID}}"
    }
   ]
  },
  {
   "title": "Booting",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(warewulf_status_node_lastseen{stage=~\"SYSTEM_OVERLAY|KERNEL\"})-(warewulf_status_node_lastseen{stage=~\"SYSTEM_OVERLAY|KERNEL\"})",
     "legendFormat": "{{nodeID}}: {{stage}}"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Sizes",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "warewulf_status_container_size", "legendFormat": "{{container}}" }
   ]
  }
 ]
}