package tpm

import (
	"fmt"

	"github.com/spf13/cobra"
)

var (
	pcrFilter    []int
	displayEvent bool
)

func GetCommand() *cobra.Command {
	baseCmd := &cobra.Command{
		DisableFlagsInUseLine: true,
		Use:                   "tpm [NODE NAME | FILE]",
		Short:                 "Verify TPM quote",
		Long:                  "Verify a TPM quote against the database or a JSON file generated by wwclient --quote",
		RunE:                  CobraRunE,
		Args:                  cobra.ExactArgs(1),
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("pcr") && !displayEvent {
				return fmt.Errorf("flag --pcr requires --eventlog")
			}
			return nil
		},
	}
	baseCmd.PersistentFlags().IntSliceVar(&pcrFilter, "pcr", []int{}, "Optional filter for PCRs (comma separated)")
	baseCmd.PersistentFlags().BoolVar(&displayEvent, "eventlog", false, "Display event log")
	return baseCmd
}
