package tpm

import (
	"github.com/spf13/cobra"
)

func GetCommand() *cobra.Command {
	baseCmd := &cobra.Command{
		DisableFlagsInUseLine: true,
		Use:                   "tpm [FILE]",
		Short:                 "Verify TPM quote",
		Long:                  "Verify a TPM quote JSON file generated by wwclient --quote",
		RunE:                  CobraRunE,
		Args:                  cobra.ExactArgs(1),
	}
	return baseCmd
}
