package tpm

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/warewulf/warewulf/internal/app/wwctl/completions"
	"github.com/warewulf/warewulf/internal/pkg/hostlist"
)

type variables struct {
	pcrFilter    []int
	displayEvent bool
	quoteFile    string
}

func GetCommand() *cobra.Command {
	vars := variables{}
	baseCmd := &cobra.Command{
		DisableFlagsInUseLine: true,
		Use:                   "tpm [OPTIONS] [NODE NAME]",
		Short:                 "Verify TPM quote",
		Long:                  "Verify a TPM quote against the database or a JSON file generated by wwclient --quote.\n" + hostlist.Docstring,
		RunE:                  CobraRunE(&vars),
		ValidArgsFunction:     completions.Nodes,
		Args:                  cobra.ArbitraryArgs,
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("pcr") && !vars.displayEvent {
				return fmt.Errorf("flag --pcr requires --eventlog")
			}
			return nil
		},
	}
	baseCmd.PersistentFlags().IntSliceVar(&vars.pcrFilter, "pcr", []int{}, "Optional filter for PCRs (comma separated)")
	baseCmd.PersistentFlags().BoolVar(&vars.displayEvent, "eventlog", false, "Display event log")
	baseCmd.PersistentFlags().StringVar(&vars.quoteFile, "file", "", "Read quote from file, json formatted")
	return baseCmd
}
