package check

import (
	"fmt"

	"github.com/spf13/cobra"
)

type variables struct {
	pcrFilter    []int
	displayEvent bool
}

func GetCommand() *cobra.Command {
	vars := variables{}
	baseCmd := &cobra.Command{
		DisableFlagsInUseLine: true,
		Use:                   "check [OPTIONS] [FILE]",
		Short:                 "Check TPM quote from file",
		Long:                  "Check a TPM quote from a JSON file generated by wwclient --quote.",
		RunE:                  CobraRunE(&vars),
		Args:                  cobra.MinimumNArgs(1),
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("pcr") && !vars.displayEvent {
				return fmt.Errorf("flag --pcr requires --eventlog")
			}
			return nil
		},
	}
	baseCmd.Flags().IntSliceVar(&vars.pcrFilter, "pcr", []int{}, "Optional filter for PCRs (comma separated)")
	baseCmd.Flags().BoolVar(&vars.displayEvent, "eventlog", false, "Display event log")
	return baseCmd
}
