// Package testutil implements utility functions to assist with testing.
package testutil

import (
	"bytes"
	"io"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
)

// CaptureOutput returns two strings representing the value of stdout and
// stderr as generated by calling the input function.
//
// The capturing process is not thread safe.
func CaptureOutput(t *testing.T, f func()) (string, string) {
	oldout := os.Stdout
	out_r, out_w, _ := os.Pipe()
	os.Stdout = out_w

	olderr := os.Stderr
	err_r, err_w, _ := os.Pipe()
	os.Stderr = err_w

	f()

	out_w.Close()
	err_w.Close()

	os.Stdout = oldout
	var outbuf bytes.Buffer
	{
		_, err := io.Copy(&outbuf, out_r)
		assert.NoError(t, err)
	}

	os.Stderr = olderr
	var errbuf bytes.Buffer
	{
		_, err := io.Copy(&errbuf, err_r)
		assert.NoError(t, err)
	}

	return outbuf.String(), errbuf.String()
}
