package hosts

import (
	"bytes"
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"

	"github.com/warewulf/warewulf/internal/app/wwctl/overlay/show"
	"github.com/warewulf/warewulf/internal/pkg/config"
	"github.com/warewulf/warewulf/internal/pkg/testenv"
	"github.com/warewulf/warewulf/internal/pkg/wwlog"
)

func Test_hostsOverlay(t *testing.T) {
	hostname, _ := os.Hostname()
	env := testenv.New(t)
	defer env.RemoveAll()
	env.ImportFile("etc/warewulf/warewulf.conf", "warewulf.conf")
	assert.NoError(t, config.Get().Read(env.GetPath("etc/warewulf/warewulf.conf"), false))
	env.ImportFile("etc/warewulf/nodes.conf", "nodes.conf")
	env.ImportFile("var/lib/warewulf/overlays/hosts/rootfs/etc/hosts.ww", "../rootfs/etc/hosts.ww")

	tests := []struct {
		name string
		args []string
		log  string
		// header marks the start of the generated block; the build host's
		// own /etc/hosts content above it is machine-specific and dropped.
		header string
	}{
		{
			name: "hosts:/etc/hosts",
			args: []string{"--render", "node1", "hosts", "etc/hosts.ww"},
			log:  hosts,
		},
		{
			name:   "hosts:/etc/hosts(server)",
			args:   []string{"--render", hostname, "hosts", "etc/hosts.ww"},
			log:    hosts_server,
			header: "# Do not edit after this line",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cmd := show.GetCommand()
			cmd.SetArgs(tt.args)
			stdout := bytes.NewBufferString("")
			stderr := bytes.NewBufferString("")
			logbuf := bytes.NewBufferString("")
			cmd.SetOut(stdout)
			cmd.SetErr(stderr)
			wwlog.SetLogWriter(logbuf)
			err := cmd.Execute()
			assert.NoError(t, err)
			assert.Empty(t, stdout.String())
			assert.Empty(t, stderr.String())
			log := logbuf.String()
			if tt.header != "" {
				log = skipHeader(t, log, tt.header)
			}
			assert.Equal(t, strings.ReplaceAll(tt.log, "%HOSTNAME%", hostname), log)
		})
	}
}

// skipHeader keeps the three leading render metadata lines and everything
// from header onward.
func skipHeader(t *testing.T, log string, header string) string {
	lines := strings.SplitAfterN(log, "\n", 4)
	if !assert.Len(t, lines, 4, "expected render metadata lines before body") {
		return log
	}
	meta, body := strings.Join(lines[:3], ""), lines[3]
	idx := strings.Index(body, header)
	if !assert.GreaterOrEqual(t, idx, 0, "header %q not found in rendered output", header) {
		return log
	}
	return meta + body[idx:]
}

const hosts string = `backupFile: true
writeFile: true
Filename: etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

# Warewulf Server
192.168.0.1 %HOSTNAME% warewulf
# Entry for node1
192.168.4.21 node1-ipmi
192.168.3.21 node1 node1-default node1-wwnet0
192.168.3.22  node1-secondary node1-wwnet1
# Entry for node2
192.168.3.23 node2 node2-default node2-wwnet0

# Warewulf Ipv6
2001:db8::1 %HOSTNAME% warewulf
# Entry for node1
2001:db8::111 node1 node1-default node1-wwnet0
2001:db8::112  node1-secondary node1-wwnet1
# Entry for node2
2001:db8::121 node2 node2-default node2-wwnet0
`

const hosts_server string = `backupFile: true
writeFile: true
Filename: etc/hosts
# Do not edit after this line
# This block is autogenerated by warewulf

# Warewulf Server
192.168.0.1 %HOSTNAME% warewulf
# Entry for node1
192.168.4.21 node1-ipmi
192.168.3.21 node1 node1-default node1-wwnet0
192.168.3.22  node1-secondary node1-wwnet1
# Entry for node2
192.168.3.23 node2 node2-default node2-wwnet0

# Warewulf Ipv6
2001:db8::1 %HOSTNAME% warewulf
# Entry for node1
2001:db8::111 node1 node1-default node1-wwnet0
2001:db8::112  node1-secondary node1-wwnet1
# Entry for node2
2001:db8::121 node2 node2-default node2-wwnet0
`
