#!/bin/sh

echo "Hello from WWINIT"

for i in /warewulf/init.d/*; do
    NAME=`basename $i`
    echo "Launching: $NAME"
    sh "$i"
done

/bin/bash

INIT=$WWINIT
echo "Cleaning up"
unset WWCONTAINER
unset WWHOSTNAME
unset WWROOT
unset WWINIT
unset WWIPMI_IPADDR
unset WWIPMI_NETMASK
unset WWIPMI_GATEWAY
unset WWIPMI_USER
unset WWIPMI_PASSWORD

echo "Calling $INIT..."
echo

sleep 2
exec $INIT
