#!/bin/sh

echo "Hello from WWINIT"

. /warewulf/config

for i in /warewulf/init.d/*; do
    NAME=`basename $i`
    echo "Launching: $NAME"
    sh "$i"
done

/bin/bash


echo "Calling $WWINIT..."
echo

sleep 2
exec $WWINIT
