#!/bin/sh

echo "Hello from WWINIT"

. /warewulf/config

myPATH=/warewulf/init.d
ls -1 $myPATH/ | while read -r NAME; do
    echo "Launching: $NAME"
    sh "$myPATH/$NAME"
done

echo "Calling $WWINIT..."
echo

sleep 2
exec $WWINIT
