#!/bin/sh

echo "Hello from WWINIT"

. /warewulf/config

myPATH=/warewulf/init.d
while read -r NAME; do
#        if [ -x $myPATH/$NAME ]
#        then
               echo "Launching: $NAME"
               sh "$myPATH/$NAME"

#        fi
done <<EOF
# `ls $myPATH/*.sh`
`ls $myPATH/`
EOF

echo "Calling $WWINIT..."
echo

sleep 2
exec $WWINIT

