package tftproot

import (
	"bytes"
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/warewulf/warewulf/internal/app/wwctl/overlay/show"
	"github.com/warewulf/warewulf/internal/pkg/config"
	"github.com/warewulf/warewulf/internal/pkg/testenv"
	"github.com/warewulf/warewulf/internal/pkg/wwlog"
)

func Test_tftprootOverlay(t *testing.T) {
	hostname, _ := os.Hostname()
	env := testenv.New(t)
	defer env.RemoveAll()
	env.ImportFile("etc/warewulf/warewulf.conf", "warewulf.conf")
	assert.NoError(t, config.Get().Read(env.GetPath("etc/warewulf/warewulf.conf"), false))
	env.ImportFile("etc/warewulf/nodes.conf", "nodes.conf")
	env.ImportFile("var/lib/warewulf/overlays/tftproot/rootfs/grub.cfg.ww", "../rootfs/grub.cfg.ww")

	tests := []struct {
		name string
		args []string
		log  string
	}{
		{
			// grub.cfg.ww redirects its output into the TFTP root with file(),
			// so the rendered file name is absolute rather than "grub.cfg".
			name: "tftproot:grub.cfg",
			args: []string{"--render-host", "tftproot", "grub.cfg.ww"},
			log:  tftproot_grub_cfg,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			cmd := show.GetCommand()
			cmd.SetArgs(tt.args)
			stdout := bytes.NewBufferString("")
			stderr := bytes.NewBufferString("")
			logbuf := bytes.NewBufferString("")
			cmd.SetOut(stdout)
			cmd.SetErr(stderr)
			wwlog.SetLogWriter(logbuf)
			assert.NoError(t, cmd.Execute())
			assert.Empty(t, stdout.String())
			assert.Empty(t, stderr.String())
			log := skipBuildInfo(logbuf.String())
			expected := strings.ReplaceAll(tt.log, "%HOSTNAME%", hostname)
			expected = strings.ReplaceAll(expected, "%TFTPROOT%", config.Get().TFTP.TftpRoot)
			assert.Equal(t, expected, log)
		})
	}
}

// skipBuildInfo drops the "# Time:" and "# Source:" header lines, which are
// not reproducible between runs.
func skipBuildInfo(log string) (newlog string) {
	for _, line := range strings.SplitAfter(log, "\n") {
		if strings.HasPrefix(line, "# Time:") || strings.HasPrefix(line, "# Source:") {
			continue
		}
		newlog = newlog + line
	}
	return
}

const tftproot_grub_cfg string = `backupFile: true
writeFile: true
Filename: %TFTPROOT%/warewulf/grub.cfg

# This file is autogenerated by warewulf
# Host:   %HOSTNAME%
echo "================================================================================"
echo "Warewulf v4 now iXPE booting with grub"
echo "================================================================================"
smbios --type 3 --get-string 8 --set assetkey
set timeout=2
# Must chainload in order to get kernel args for specific node
menuentry "Load specific configfile" {
    conf="(http,192.168.0.1:9873)/grub/${net_default_mac}?assetkey=${assetkey}"
    configfile $conf
}
menuentry "Chainload shim from image" {
    shim="(http,192.168.0.1:9873)/efiboot/shim.efi?wwid=${net_default_mac}&assetkey=${assetkey}"
    chainloader ${shim}
}
menuentry "UEFI Firmware Settings" --id "uefi-firmware" {
    fwsetup
}
menuentry "System restart" {
    echo "System rebooting..."
    reboot
}
menuentry "System shutdown" {
    echo "System shutting down..."
    halt
}
`
