#!/bin/sh

. /warewulf/config

echo "Warewulf prescript: VNFS fixes"
echo

add_broken_shadow() {
    if [ -f "${1}" ]; then
        echo "Adding broken_shadow to ${1}..."
        sed -i -e '/^account.*pam_unix\.so\s*$/s/\s*$/\ broken_shadow/' "${1}"
    fi
}

add_broken_shadow /etc/pam.d/system-auth
add_broken_shadow /etc/pam.d/password-auth
add_broken_shadow /etc/pam.d/common-account

echo "Adjusting root directory permissions..."
chmod 755 /
