package nfsd

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/warewulf/warewulf/internal/app/wwctl/overlay/show"
	"github.com/warewulf/warewulf/internal/pkg/config"
	"github.com/warewulf/warewulf/internal/pkg/testenv"
	"github.com/warewulf/warewulf/internal/pkg/wwlog"
)

func Test_nfsdOverlay(t *testing.T) {
	env := testenv.New(t)
	defer env.RemoveAll()
	env.ImportFile("etc/warewulf/nodes.conf", "nodes.conf")
	env.ImportFile("var/lib/warewulf/overlays/nfsd/rootfs/etc/exports.ww", "../rootfs/etc/exports.ww")

	tests := []struct {
		name string
		conf string
		args []string
		log  string
	}{
		{
			name: "nfsd:/etc/exports",
			conf: "warewulf.conf",
			args: []string{"--render", "host", "nfsd", "etc/exports.ww"},
			log:  nfsd_exports,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			env.ImportFile("etc/warewulf/warewulf.conf", tt.conf)
			assert.NoError(t, config.Get().Read(env.GetPath("etc/warewulf/warewulf.conf"), false))
			cmd := show.GetCommand()
			cmd.SetArgs(tt.args)
			stdout := bytes.NewBufferString("")
			stderr := bytes.NewBufferString("")
			logbuf := bytes.NewBufferString("")
			cmd.SetOut(stdout)
			cmd.SetErr(stderr)
			wwlog.SetLogWriter(logbuf)
			assert.NoError(t, cmd.Execute())
			assert.Empty(t, stdout.String())
			assert.Empty(t, stderr.String())
			assert.Equal(t, tt.log, logbuf.String())
		})
	}
}

const nfsd_exports string = `backupFile: true
writeFile: true
Filename: etc/exports
# This file is autogenerated by warewulf
/home 192.168.0.0/255.255.255.0(rw,sync) 2001:db8::/64(rw,sync)
/opt 192.168.0.0/255.255.255.0(ro,sync,no_root_squash) 2001:db8::/64(ro,sync,no_root_squash)

`
