nodeprofiles:
  svcprofile:
    resources:
      localusers:
        - name: profileuser
          uid: 3001
          gid: 3001
          home: /var/lib/profilesvc
          shell: /sbin/nologin
nodes:
  node1:
    image name: rockylinux-9
  node2:
    image name: rockylinux-9
    tags:
      PasswordlessRoot: true
  node3:
    image name: rockylinux-9
    resources:
      localusers:
        - name: dbuser
          uid: 1001
          gid: 1002
          gecos: "Database User"
          home: /var/lib/db
          shell: /bin/nologin
        - name: appuser
          uid: 1003
          gid: 1004
          gecos: "Application User"
          home: /opt/app
          shell: /bin/bash
      localgroups:
        - name: dbgroup
          gid: 1002
          members:
            - dbuser
            - appuser
        - name: appgroup
          gid: 1004
          members:
            - appuser
  node4:
    image name: rockylinux-9
    resources:
      localusers:
        - name: svcuser
          uid: 2001
          gid: 2001
          home: /
          shell: /sbin/nologin
  node5:
    image name: rockylinux-9
    resources:
      localusers:
        - name: collideuser
          uid: 1500
          gid: 1000
          home: /var/lib/collide
          shell: /bin/bash
  node6:
    image name: rockylinux-9
    profiles:
      - svcprofile
