FROM docker.io/library/centos:7

RUN yum update -y \
    && yum install -y \
      coreutils \
      cpio \
      dhclient \
      e2fsprogs \
      ethtool \
      findutils \
      initscripts \
      ipmitool \
      iproute \
      kernel \
      net-tools \
      network-scripts \
      nfs-utils \
      openssh-clients \
      openssh-server \
      pciutils \
      psmisc \
      rsync \
      rsyslog \
      strace \
      wget \
      which \
      words \
    && yum clean all \
    && sed -i -e '/^account.*pam_unix\.so\s*$/s/\s*$/\ broken_shadow/' /etc/pam.d/system-auth \
    && sed -i -e '/^account.*pam_unix\.so\s*$/s/\s*$/\ broken_shadow/' /etc/pam.d/password-auth \
    && rm -f /etc/sysconfig/network-scripts/ifcfg-e* \
    && systemctl unmask console-getty.service dev-hugepages.mount getty.target sys-fs-fuse-connections.mount systemd-logind.service systemd-remount-fs.service \
    && systemctl enable network

COPY excludes /etc/warewulf/excludes
COPY container_exit.sh /etc/warewulf/container_exit.sh
