package dhcpd

import (
	"bytes"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/warewulf/warewulf/internal/app/wwctl/overlay/show"
	"github.com/warewulf/warewulf/internal/pkg/config"
	"github.com/warewulf/warewulf/internal/pkg/testenv"
	"github.com/warewulf/warewulf/internal/pkg/wwlog"
)

func Test_dhcpdOverlay(t *testing.T) {
	env := testenv.New(t)
	defer env.RemoveAll()
	env.ImportFile("etc/warewulf/nodes.conf", "nodes.conf")
	env.ImportFile("var/lib/warewulf/overlays/dhcpd/rootfs/etc/dhcp/dhcpd.conf.ww", "../rootfs/etc/dhcp/dhcpd.conf.ww")

	tests := []struct {
		name string
		conf string
		args []string
		log  string
	}{
		{
			name: "dhcpd:/etc/dhcp/dhcpd.conf",
			conf: "warewulf.conf",
			args: []string{"--render-host", "dhcpd", "etc/dhcp/dhcpd.conf.ww"},
			log:  dhcpd_conf,
		},
		{
			name: "dhcpd:/etc/dhcp/dhcpd.conf(static)",
			conf: "warewulf.conf-static",
			args: []string{"--render-host", "dhcpd", "etc/dhcp/dhcpd.conf.ww"},
			log:  dhcpd_conf_static,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			env.ImportFile("etc/warewulf/warewulf.conf", tt.conf)
			assert.NoError(t, config.Get().Read(env.GetPath("etc/warewulf/warewulf.conf"), false))
			cmd := show.GetCommand()
			cmd.SetArgs(tt.args)
			stdout := bytes.NewBufferString("")
			stderr := bytes.NewBufferString("")
			logbuf := bytes.NewBufferString("")
			cmd.SetOut(stdout)
			cmd.SetErr(stderr)
			wwlog.SetLogWriter(logbuf)
			assert.NoError(t, cmd.Execute())
			assert.Empty(t, stdout.String())
			assert.Empty(t, stderr.String())
			assert.Equal(t, tt.log, logbuf.String())
		})
	}
}

const dhcpd_conf string = `backupFile: true
writeFile: true
Filename: etc/dhcp/dhcpd.conf
# This file is autogenerated by warewulf

allow booting;
allow bootp;
ddns-update-style interim;
authoritative;

option space ipxe;

# Tell iPXE to not wait for ProxyDHCP requests to speed up boot.
option ipxe.no-pxedhcp code 176 = unsigned integer 8;
option ipxe.no-pxedhcp 1;

option space PXE;
option PXE.mtftp-ip    code 1 = ip-address;
option PXE.mtftp-cport code 2 = unsigned integer 16;
option PXE.mtftp-sport code 3 = unsigned integer 16;
option PXE.mtftp-tmout code 4 = unsigned integer 8;
option PXE.mtftp-delay code 5 = unsigned integer 8;

option architecture-type   code 93  = unsigned integer 16;
if exists user-class and option user-class = "iPXE" {
    filename "http://192.168.0.1:9873/ipxe/${mac:hexhyp}?assetkey=${asset}&uuid=${uuid}";
} else {
    if option architecture-type = 00:00 {
        filename "/warewulf/undionly.kpxe";
    }
    if option architecture-type = 00:07 {
        filename "/warewulf/ipxe-snponly-x86_64.efi";
    }
    if option architecture-type = 00:09 {
        filename "/warewulf/ipxe-snponly-x86_64.efi";
    }
    if option architecture-type = 00:0B {
        filename "/warewulf/snponly.efi";
    }
}
subnet 192.168.0.0 netmask 255.255.255.0 {
    max-lease-time 120;
    range 192.168.0.100 192.168.0.199;
    next-server 192.168.0.1;
}
`

const dhcpd_conf_static string = `backupFile: true
writeFile: true
Filename: etc/dhcp/dhcpd.conf
# This file is autogenerated by warewulf

allow booting;
allow bootp;
ddns-update-style interim;
authoritative;

option space ipxe;

# Tell iPXE to not wait for ProxyDHCP requests to speed up boot.
option ipxe.no-pxedhcp code 176 = unsigned integer 8;
option ipxe.no-pxedhcp 1;

option space PXE;
option PXE.mtftp-ip    code 1 = ip-address;
option PXE.mtftp-cport code 2 = unsigned integer 16;
option PXE.mtftp-sport code 3 = unsigned integer 16;
option PXE.mtftp-tmout code 4 = unsigned integer 8;
option PXE.mtftp-delay code 5 = unsigned integer 8;

option architecture-type   code 93  = unsigned integer 16;
if exists user-class and option user-class = "iPXE" {
    filename "http://192.168.0.1:9873/ipxe/${mac:hexhyp}?assetkey=${asset}&uuid=${uuid}";
} else {
    if option architecture-type = 00:00 {
        filename "/warewulf/undionly.kpxe";
    }
    if option architecture-type = 00:07 {
        filename "/warewulf/ipxe-snponly-x86_64.efi";
    }
    if option architecture-type = 00:09 {
        filename "/warewulf/ipxe-snponly-x86_64.efi";
    }
    if option architecture-type = 00:0B {
        filename "/warewulf/snponly.efi";
    }
}
subnet 192.168.0.0 netmask 255.255.255.0 {
    max-lease-time 120;
    range 192.168.0.100 192.168.0.199;
    next-server 192.168.0.1;
}
host node1-default
{
    hardware ethernet e6:92:39:49:7b:03;
    fixed-address 192.168.3.21;
    option host-name "node1";
}

host node1-secondary
{
    hardware ethernet 9a:77:29:73:14:f1;
    fixed-address 192.168.3.22;
}


host node2-default
{
    hardware ethernet e6:92:39:49:7b:04;
    fixed-address 192.168.3.23;
    option host-name "node2";
}



`
